export const ASSET_STATUSES = [
  'Available',
  'Allocated',
  'Under Maintenance',
  'Damaged',
  'Scrap',
  'Replaced',
]

export const ASSET_CONDITIONS = ['New', 'Good', 'Fair', 'Poor']

export const ASSET_CATEGORIES = [
  'Laptop',
  'Desktop',
  'Monitor',
  'Printer',
  'Phone',
  'Network',
  'Peripheral',
  'Display',
  'Server',
]

export const STATIC_ASSETS = [
  {
    id: 1,
    asset_tag: 'IT-2024-001',
    model_name: 'Dell Latitude 5540',
    serial_number: 'SN-DL-001234',
    category: 'Laptop',
    vendor: 'Dell India Pvt Ltd',
    status: 'Allocated',
    condition: 'Good',
    purchase_date: '2024-01-15',
    warranty_expiry: '2027-01-15',
    assigned_to: 'Rahul Sharma',
  },
  {
    id: 2,
    asset_tag: 'IT-2024-002',
    model_name: 'HP EliteBook 840 G10',
    serial_number: 'SN-HP-005678',
    category: 'Laptop',
    vendor: 'HP India',
    status: 'Available',
    condition: 'Good',
    purchase_date: '2024-02-10',
    warranty_expiry: '2027-02-10',
    assigned_to: null,
  },
  {
    id: 3,
    asset_tag: 'IT-2024-003',
    model_name: 'Apple MacBook Pro M3',
    serial_number: 'SN-AP-009012',
    category: 'Laptop',
    vendor: 'Apple India',
    status: 'Allocated',
    condition: 'New',
    purchase_date: '2024-03-05',
    warranty_expiry: '2027-03-05',
    assigned_to: 'Priya Menon',
  },
  {
    id: 4,
    asset_tag: 'IT-2024-004',
    model_name: 'Lenovo ThinkPad X1 Carbon',
    serial_number: 'SN-LN-003456',
    category: 'Laptop',
    vendor: 'Lenovo India',
    status: 'Under Maintenance',
    condition: 'Fair',
    purchase_date: '2023-06-20',
    warranty_expiry: '2026-06-20',
    assigned_to: null,
  },
  {
    id: 5,
    asset_tag: 'IT-2024-005',
    model_name: 'Dell OptiPlex 3090',
    serial_number: 'SN-DL-007890',
    category: 'Desktop',
    vendor: 'Dell India Pvt Ltd',
    status: 'Available',
    condition: 'Good',
    purchase_date: '2024-01-28',
    warranty_expiry: '2027-01-28',
    assigned_to: null,
  },
  {
    id: 6,
    asset_tag: 'IT-2024-006',
    model_name: 'HP LaserJet Pro M428',
    serial_number: 'SN-HP-011234',
    category: 'Printer',
    vendor: 'HP India',
    status: 'Allocated',
    condition: 'Good',
    purchase_date: '2023-08-14',
    warranty_expiry: '2026-08-14',
    assigned_to: 'Finance Team',
  },
  {
    id: 7,
    asset_tag: 'IT-2024-007',
    model_name: 'Cisco IP Phone 8841',
    serial_number: 'SN-CS-015678',
    category: 'Phone',
    vendor: 'Cisco Systems',
    status: 'Available',
    condition: 'Good',
    purchase_date: '2023-11-02',
    warranty_expiry: '2026-11-02',
    assigned_to: null,
  },
  {
    id: 8,
    asset_tag: 'IT-2024-008',
    model_name: 'Dell 27" Monitor P2722H',
    serial_number: 'SN-DL-019012',
    category: 'Monitor',
    vendor: 'Dell India Pvt Ltd',
    status: 'Damaged',
    condition: 'Poor',
    purchase_date: '2022-04-18',
    warranty_expiry: '2025-04-18',
    assigned_to: null,
  },
  {
    id: 9,
    asset_tag: 'IT-2023-009',
    model_name: 'HP Deskjet 2700',
    serial_number: 'SN-HP-023456',
    category: 'Printer',
    vendor: 'HP India',
    status: 'Scrap',
    condition: 'Poor',
    purchase_date: '2021-07-30',
    warranty_expiry: '2024-07-30',
    assigned_to: null,
  },
  {
    id: 10,
    asset_tag: 'IT-2024-010',
    model_name: 'Logitech MX Keys Keyboard',
    serial_number: 'SN-LG-027890',
    category: 'Peripheral',
    vendor: 'Logitech',
    status: 'Available',
    condition: 'New',
    purchase_date: '2024-04-22',
    warranty_expiry: '2027-04-22',
    assigned_to: null,
  },
  {
    id: 11,
    asset_tag: 'IT-2024-011',
    model_name: 'Dell UltraSharp 24" U2422H',
    serial_number: 'SN-DL-031234',
    category: 'Monitor',
    vendor: 'Dell India Pvt Ltd',
    status: 'Allocated',
    condition: 'Good',
    purchase_date: '2024-02-28',
    warranty_expiry: '2027-02-28',
    assigned_to: 'Amit Kulkarni',
  },
  {
    id: 12,
    asset_tag: 'IT-2023-012',
    model_name: 'Cisco Catalyst 2960 Switch',
    serial_number: 'SN-CS-035678',
    category: 'Network',
    vendor: 'Cisco Systems',
    status: 'Available',
    condition: 'Good',
    purchase_date: '2023-09-15',
    warranty_expiry: '2026-09-15',
    assigned_to: null,
  },
  {
    id: 13,
    asset_tag: 'IT-2023-013',
    model_name: 'Polycom VVX 500 Conference',
    serial_number: 'SN-PL-039012',
    category: 'Phone',
    vendor: 'Polycom',
    status: 'Under Maintenance',
    condition: 'Fair',
    purchase_date: '2022-12-10',
    warranty_expiry: '2025-12-10',
    assigned_to: null,
  },
  {
    id: 14,
    asset_tag: 'IT-2022-014',
    model_name: 'Samsung 55" Smart Display',
    serial_number: 'SN-SM-043456',
    category: 'Display',
    vendor: 'Samsung India',
    status: 'Replaced',
    condition: 'Good',
    purchase_date: '2022-02-05',
    warranty_expiry: '2025-02-05',
    assigned_to: null,
  },
  {
    id: 15,
    asset_tag: 'IT-2023-015',
    model_name: 'Dell PowerEdge R340 Server',
    serial_number: 'SN-DL-047890',
    category: 'Server',
    vendor: 'Dell India Pvt Ltd',
    status: 'Allocated',
    condition: 'Good',
    purchase_date: '2023-05-18',
    warranty_expiry: '2028-05-18',
    assigned_to: 'IT Department',
  },
]
